### ISSUE TITLE
Method 1 launch failure: Can't contact GHunt on 127.0.0.1:60067

### ISSUE THREAD

**Issue by bbeale** [mxrch/ghunt_companion#1]
Tested on Chromium/Brave and Firefox. Launching Method 1 results in an error. 

Installation works normally, as does Method 2.

![Screen Shot 2021-11-30 at 8 26 28 PM](https://user-images.githubusercontent.com/9686813/144155121-79c8859e-d7ff-4293-8027-54ca29b0a014.png)

**Comment by mxrch** [comment]
Hi @bbeale ,
1) Did you started the check_and_gen.py and put GHunt in listening mode ?
2) If so, do you have en error ? If no, can you check if a service is already using this port ?
3) Do you use GHunt in a docker ? If no, what is your operating system and your Python version ?
4) Does your browser performs a sort of sandbox that blocks your outgoing connections, maybe an extension for that ?

**Comment by mxrch** [comment]
![IMG_20211201_025409.jpg](https://user-images.githubusercontent.com/17338428/144157555-eae8e545-c790-44d8-be56-13d2315b6800.jpg)
